name: Java CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check Versions
        run: |
          java -version
          mvn -version

      - name: Build Application
        run: mvn clean package

      - name: Show Target Directory
        run: ls -la target

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: calculator-jar
          path: target/*.jar
